Repository woorifisa-projects-3rd/WithBeeTravel-BE, pull requests merged in 2024-11, with the labels that each got.

#24 [build] ci/cd main에 합쳐질 때 수행하도록 설정
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
Labels: feat

#23 [feat]: Entity 추가
  src/main/java/withbeetravel/domain/Category.java
  src/main/java/withbeetravel/domain/Country.java
  src/main/java/withbeetravel/domain/CurrencyUnit.java
  src/main/java/withbeetravel/domain/PaymentParticipatedMember.java
  src/main/java/withbeetravel/domain/RequestStatus.java
  src/main/java/withbeetravel/domain/SettlementRequest.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/domain/SettlementStatus.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/domain/TravelCountry.java
  src/main/java/withbeetravel/domain/TravelMember.java
  src/main/java/withbeetravel/domain/TravelMemberSettlementHistory.java
  src/main/java/withbeetravel/domain/User.java
Labels: feat

#29 [feat/TK-69]: Entity 수정
  src/main/java/withbeetravel/domain/Account.java
  src/main/java/withbeetravel/domain/History.java
  src/main/java/withbeetravel/domain/PaymentParticipatedMember.java
  src/main/java/withbeetravel/domain/Product.java
  src/main/java/withbeetravel/domain/SettlementRequest.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/domain/TravelCountry.java
  src/main/java/withbeetravel/domain/TravelMember.java
  src/main/java/withbeetravel/domain/TravelMemberSettlementHistory.java
  src/main/java/withbeetravel/domain/User.java
Labels: feat

#31 [fix/TK-113]: Entity 오류 수정
  src/main/java/withbeetravel/domain/SharedPayment.java
Labels: bug

#34 Feat/TK-117 swagger 설정
  build.gradle
  src/main/java/withbeetravel/config/SecurityConfig.java
  src/main/java/withbeetravel/config/SwaggerConfig.java
  src/main/java/withbeetravel/controller/PaymentController.java
  src/main/java/withbeetravel/controller/docs/PaymentControllerDocs.java
  src/main/java/withbeetravel/dto/ChooseParticipantsRequestDto.java
  src/main/java/withbeetravel/exception/dto/ErrorResponseDto.java
Labels: feat

#38 [fix] 엔티티 수정
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/domain/SharedPayment.java
Labels: bug

#39 [refactor]: 엔티티 수정
  src/main/java/withbeetravel/domain/SharedPayment.java
Labels: ♻️ refactor

#45 [feat/TK-132]: 커스텀 Response DTO 추가
  src/main/java/withbeetravel/dto/response/SuccessResponse.java
Labels: ✨ feature

#46 Feat/tk 135 s3 연동
  .gitignore
  build.gradle
  src/main/java/withbeetravel/WithbeetravelApplication.java
  src/main/java/withbeetravel/config/S3Config.java
  src/main/java/withbeetravel/service/S3Uploader.java
Labels: ✨ feature

#48 Feat/tk 113 여행 기록 관련 api 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/aspect/CheckTravelAccess.java
  src/main/java/withbeetravel/aspect/CheckTravelAndSharedPaymentAccess.java
  src/main/java/withbeetravel/aspect/TravelAccessAspect.java
  src/main/java/withbeetravel/aspect/TravelAndSharedPaymentAccessAspect.java
  src/main/java/withbeetravel/controller/PaymentController.java
  src/main/java/withbeetravel/controller/SharedPaymentController.java
  src/main/java/withbeetravel/controller/docs/PaymentControllerDocs.java
  src/main/java/withbeetravel/controller/docs/SharedPaymentControllerDocs.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/dto/request/ChooseParticipantsRequest.java
  src/main/java/withbeetravel/dto/response/ErrorResponse.java
  src/main/java/withbeetravel/dto/response/SharedPaymentRecordResponse.java
  src/main/java/withbeetravel/dto/response/SuccessResponse.java
  src/main/java/withbeetravel/exception/error/PaymentErrorCode.java
  src/main/java/withbeetravel/exception/error/ValidationErrorCode.java
  src/main/java/withbeetravel/exception/handler/CustomExceptionHandler.java
  src/main/java/withbeetravel/repository/SharedPaymentRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/repository/TravelRepository.java
  src/main/java/withbeetravel/repository/UserRepository.java
  src/main/java/withbeetravel/service/SharedPaymentService.java
  src/main/java/withbeetravel/service/SharedPaymentServiceImpl.java
Labels: ✨ feature

#50 [Feat/TK-128] 지출 세부 내역 조회 API 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/config/CorsConfig.java
  src/main/java/withbeetravel/controller/SettlementController.java
  src/main/java/withbeetravel/domain/RequestStatus.java
  src/main/java/withbeetravel/domain/SettlementRequest.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/domain/TravelMemberSettlementHistory.java
  src/main/java/withbeetravel/dto/settlement/ShowMyDetailPaymentResponse.java
  src/main/java/withbeetravel/dto/settlement/ShowMyTotalPaymentResponse.java
  src/main/java/withbeetravel/dto/settlement/ShowOtherSettlementResponse.java
  src/main/java/withbeetravel/dto/settlement/ShowSettlementDetailResponse.java
  src/main/java/withbeetravel/exception/error/SettlementErrorCode.java
  src/main/java/withbeetravel/repository/PaymentParticipatedMemberRepository.java
  src/main/java/withbeetravel/repository/SettlementRequestRepository.java
  src/main/java/withbeetravel/repository/TravelMemberSettlementHistoryRepository.java
  src/main/java/withbeetravel/repository/UserRepository.java
  src/main/java/withbeetravel/service/settlement/SettlementService.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#59 [Feat/TK-148] 정산 요청 API 구현
  src/main/java/withbeetravel/controller/SettlementController.java
  src/main/java/withbeetravel/dto/response/settlement/ShowMyDetailPaymentResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowMyTotalPaymentResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowOtherSettlementResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowSettlementDetailResponse.java
  src/main/java/withbeetravel/repository/SettlementRequestLogRepository.java
  src/main/java/withbeetravel/repository/SharedPaymentRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/settlement/SettlementService.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#53 Feat/tk 138 허니캡슐 api 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/sharedPayment/SharedPaymentRecordController.java
  src/main/java/withbeetravel/controller/sharedPayment/docs/SharedPaymentRecordControllerDocs.java
  src/main/java/withbeetravel/controller/travel/HoneyCapsuleController.java
  src/main/java/withbeetravel/controller/travel/docs/HoneyCapsuleControllerDocs.java
  src/main/java/withbeetravel/dto/request/ChooseParticipantsRequest.java
  src/main/java/withbeetravel/dto/response/shardPayment/SharedPaymentRecordResponse.java
  src/main/java/withbeetravel/dto/response/travel/HoneyCapsuleResponse.java
  src/main/java/withbeetravel/repository/SharedPaymentRepository.java
  src/main/java/withbeetravel/service/global/S3Uploader.java
  src/main/java/withbeetravel/service/sharedPayment/SharedPaymentRecordService.java
  src/main/java/withbeetravel/service/sharedPayment/SharedPaymentRecoredServiceImpl.java
  src/main/java/withbeetravel/service/travel/HoneyCapsuleService.java
  src/main/java/withbeetravel/service/travel/HoneyCapsuleServiceImpl.java
Labels: ✨ feature

#55 Feat/tk 142 정산 참여 인원 수정 api 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentParticipantController.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentRecordController.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentParticipantControllerDocs.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRecordControllerDocs.java
  src/main/java/withbeetravel/controller/travel/docs/HoneyCapsuleControllerDocs.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/dto/request/payment/SharedPaymentParticipateRequest.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentRecordResponse.java
  src/main/java/withbeetravel/exception/error/PaymentErrorCode.java
  src/main/java/withbeetravel/repository/PaymentParticipatedMemberRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/payment/SharedPaymentParticipantService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentParticipantServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecordService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecoredServiceImpl.java
Labels: ✨ feature

#35 Feat/tk 120 신규 계좌 개설 api 구현
  src/main/java/withbeetravel/config/CorsConfig.java
  src/main/java/withbeetravel/config/SecurityConfig.java
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/controller/banking/HistoryController.java
  src/main/java/withbeetravel/domain/Account.java
  src/main/java/withbeetravel/domain/History.java
  src/main/java/withbeetravel/domain/Product.java
  src/main/java/withbeetravel/domain/TravelMember.java
  src/main/java/withbeetravel/dto/banking/account/AccountNumberRequest.java
  src/main/java/withbeetravel/dto/banking/account/AccountOwnerNameResponse.java
  src/main/java/withbeetravel/dto/banking/account/AccountRequest.java
  src/main/java/withbeetravel/dto/banking/account/AccountResponse.java
  src/main/java/withbeetravel/dto/banking/account/DepositRequest.java
  src/main/java/withbeetravel/dto/banking/account/HistoryResponse.java
  src/main/java/withbeetravel/dto/banking/account/TransferRequest.java
  src/main/java/withbeetravel/exception/error/BankingErrorCode.java
  src/main/java/withbeetravel/repository/AccountRepository.java
  src/main/java/withbeetravel/repository/HistoryRepository.java
  src/main/java/withbeetravel/repository/UserRepository.java
  src/main/java/withbeetravel/service/banking/AccountService.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/banking/HistoryService.java
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: ✨ feature

#67 [style/TK-155]: 패키지 구조 수정
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/controller/settlement/SettlementController.java
  src/main/java/withbeetravel/dto/banking/account/AccountNumberRequest.java
  src/main/java/withbeetravel/dto/request/account/AccountNumberRequest.java
  src/main/java/withbeetravel/dto/request/account/AccountRequest.java
  src/main/java/withbeetravel/dto/request/account/DepositRequest.java
  src/main/java/withbeetravel/dto/request/account/TransferRequest.java
  src/main/java/withbeetravel/dto/response/account/AccountOwnerNameResponse.java
  src/main/java/withbeetravel/dto/response/account/AccountResponse.java
  src/main/java/withbeetravel/dto/response/account/HistoryResponse.java
  src/main/java/withbeetravel/service/banking/AccountService.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/banking/HistoryService.java
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: 🚨 hotfix

#43 [Feat/TK-127] 여행 생성 API 구현
  build.gradle
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/config/CorsConfig.java
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/domain/Country.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/dto/request/travel/TravelRequestDto.java
  src/main/java/withbeetravel/dto/response/travel/TravelResponseDto.java
  src/main/java/withbeetravel/exception/error/TravelErrorCode.java
  src/main/java/withbeetravel/repository/AccountRepository.java
  src/main/java/withbeetravel/repository/TravelCountryRepository.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#47 [Feat/tk-133] 여행 편집 API 구현
  build.gradle
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/config/CorsConfig.java
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/domain/Country.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/dto/request/travel/TravelRequestDto.java
  src/main/java/withbeetravel/dto/response/travel/TravelResponseDto.java
  src/main/java/withbeetravel/exception/error/TravelErrorCode.java
  src/main/java/withbeetravel/repository/AccountRepository.java
  src/main/java/withbeetravel/repository/TravelCountryRepository.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#75 [Feat/TK-145] 정산 동의 API 구현
  src/main/java/withbeetravel/aspect/TravelAccessAspect.java
  src/main/java/withbeetravel/aspect/TravelAndSharedPaymentAccessAspect.java
  src/main/java/withbeetravel/controller/settlement/SettlementController.java
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/domain/SettlementRequest.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/domain/TravelMemberSettlementHistory.java
  src/main/java/withbeetravel/exception/error/SettlementErrorCode.java
  src/main/java/withbeetravel/repository/TravelMemberSettlementHistoryRepository.java
  src/main/java/withbeetravel/service/settlement/SettlementPendingService.java
  src/main/java/withbeetravel/service/settlement/SettlementPendingServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementService.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#60 Feat/tk 143 결제 내역 직접 추가 api 구현
  src/main/java/withbeetravel/controller/payment/SharedPaymentRecordController.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentRegisterController.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRecordControllerDocs.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRegisterControllerDocs.java
  src/main/java/withbeetravel/domain/CurrencyUnit.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/exception/error/ValidationErrorCode.java
  src/main/java/withbeetravel/repository/PaymentParticipatedMemberRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecordService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecoredServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
Labels: ✨ feature

#69 Feat/tk 154 위비 카드 결제 내역 공동 결제 내역에 추가
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentRegisterController.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRegisterControllerDocs.java
  src/main/java/withbeetravel/domain/Account.java
  src/main/java/withbeetravel/domain/History.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/dto/request/payment/SharedPaymentWibeeCardRegisterRequest.java
  src/main/java/withbeetravel/exception/error/BankingErrorCode.java
  src/main/java/withbeetravel/service/banking/AccountService.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
Labels: ✨ feature

#73 [hotfix]: DataLoader gitignore에 추가, User profileImage 타입 변경
  .gitignore
  src/main/java/withbeetravel/domain/User.java
Labels: 🚨 hotfix

#84 Feat/tk 156 뱅킹 상세 예외처리
  .github/workflows/depoly-desktop.yml
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/controller/banking/HistoryController.java
  src/main/java/withbeetravel/dto/request/account/CreateAccountRequest.java
  src/main/java/withbeetravel/dto/request/account/HistoryRequest.java
  src/main/java/withbeetravel/dto/response/account/AccountConnectedWibeeResponse.java
  src/main/java/withbeetravel/service/banking/AccountService.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/banking/HistoryService.java
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: ✨ feature

#87 [hotfix]: 뱅킹 에러코드 컴플리트 해결
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: 🚨 hotfix

#61 [Feat/TK-141] 공동결제내역 조회 API
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/aspect/PaymentValidation.java
  src/main/java/withbeetravel/aspect/PaymentValidationAspect.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentController.java
  src/main/java/withbeetravel/controller/travel/TravelMemberController.java
  src/main/java/withbeetravel/domain/SharedPayment.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/dto/request/payment/SharedPaymentSearchRequest.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentParticipatingMemberResponse.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentResponse.java
  src/main/java/withbeetravel/dto/response/travel/TravelMemberResponse.java
  src/main/java/withbeetravel/exception/error/PaymentErrorCode.java
  src/main/java/withbeetravel/repository/SharedPaymentRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/payment/SharedPaymentService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentServiceImpl.java
  src/main/java/withbeetravel/service/travel/TravelMemberService.java
  src/main/java/withbeetravel/service/travel/TravelMemberServiceImpl.java
Labels: ✨ feature

#83 [Feat/TK-168] 정산 취소 API 구현
  src/main/java/withbeetravel/controller/settlement/SettlementController.java
  src/main/java/withbeetravel/domain/TravelMember.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/exception/error/BankingErrorCode.java
  src/main/java/withbeetravel/repository/TravelMemberSettlementHistoryRepository.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementService.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#78 [Feat/tk -162] : 초대 코드로 가입하기 API 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/dto/request/travel/InviteCodeSignUpRequest.java
  src/main/java/withbeetravel/dto/request/travel/TravelRequest.java
  src/main/java/withbeetravel/dto/request/travel/TravelRequestDto.java
  src/main/java/withbeetravel/dto/response/travel/InviteCodeGetResponse.java
  src/main/java/withbeetravel/dto/response/travel/InviteCodeSignUpResponse.java
  src/main/java/withbeetravel/dto/response/travel/TravelResponse.java
  src/main/java/withbeetravel/exception/error/TravelErrorCode.java
  src/main/java/withbeetravel/exception/error/UserErrorCode.java
  src/main/java/withbeetravel/repository/AccountRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/repository/TravelRepository.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#93 Feat/tk 180 결제 내역 추가 에러 수정
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
Labels: 🐞bug

#101 [feat/TK-175]: 핀번호 검증 API 구현 및 User 엔티티 수정
  src/main/java/withbeetravel/controller/banking/VerifyController.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/dto/request/account/PinNumberRequest.java
  src/main/java/withbeetravel/dto/response/account/PinNumberResponse.java
  src/main/java/withbeetravel/exception/error/BankingErrorCode.java
  src/main/java/withbeetravel/service/banking/VerifyService.java
  src/main/java/withbeetravel/service/banking/VerifyServiceImpl.java
Labels: ✨ feature

#89 [Feat/TK-169] 알림창 조회 API 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/dto/request/settlementRequestLog/SettlementRequestLogDto.java
  src/main/java/withbeetravel/dto/response/settlement/ShowSettlementDetailResponse.java
  src/main/java/withbeetravel/repository/SettlementRequestLogRepository.java
  src/main/java/withbeetravel/repository/SettlementRequestRepository.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogService.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogServiceIml.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#103 [Feat/TK-187] 인증인가 구현
  build.gradle
  src/main/java/withbeetravel/config/PasswordEncoderConfig.java
  src/main/java/withbeetravel/config/SecurityConfig.java
  src/main/java/withbeetravel/controller/auth/AuthController.java
  src/main/java/withbeetravel/controller/settlement/SettlementController.java
  src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/dto/request/auth/CustomUserInfoDto.java
  src/main/java/withbeetravel/dto/request/auth/RefreshTokenDto.java
  src/main/java/withbeetravel/dto/request/auth/RoleType.java
  src/main/java/withbeetravel/dto/request/auth/SignInRequestDto.java
  src/main/java/withbeetravel/dto/request/auth/SignUpRequestDto.java
  src/main/java/withbeetravel/dto/response/auth/SignInResponseDto.java
  src/main/java/withbeetravel/exception/error/AuthErrorCode.java
  src/main/java/withbeetravel/jwt/JwtAuthFilter.java
  src/main/java/withbeetravel/jwt/JwtUtil.java
  src/main/java/withbeetravel/jwt/RefreshToken.java
  src/main/java/withbeetravel/jwt/TokenStatus.java
  src/main/java/withbeetravel/repository/UserRepository.java
  src/main/java/withbeetravel/security/CustomUserDetails.java
  src/main/java/withbeetravel/security/UserAuthorizationUtil.java
  src/main/java/withbeetravel/service/auth/AuthService.java
  src/main/java/withbeetravel/service/auth/AuthServiceImpl.java
  src/main/java/withbeetravel/service/auth/CustomUserDetailsService.java
  src/main/java/withbeetravel/service/auth/RefreshTokenService.java
  src/main/java/withbeetravel/service/auth/RefreshTokenServiceImpl.java
Labels: ✨ feature

#99 [feat/TK-183]: 여행 홈 GET API
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/domain/Category.java
  src/main/java/withbeetravel/domain/Travel.java
  src/main/java/withbeetravel/dto/response/travel/TravelHomeResponse.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#102 [Feat/TK-141] 생성형 AI 카테고리 분류 로직 추가
  build.gradle
  src/main/java/withbeetravel/config/OpenAIConfig.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentController.java
  src/main/java/withbeetravel/domain/Category.java
  src/main/java/withbeetravel/dto/request/payment/SharedPaymentSearchRequest.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentResponse.java
  src/main/java/withbeetravel/repository/SharedPaymentRepository.java
  src/main/java/withbeetravel/service/payment/SharedPaymentCategoryClassificationService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentCategoryClassificationServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentServiceImpl.java
Labels: ✨ feature

#88 [feat/TK-176]:여행 목록 API 구현
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/dto/response/travel/TravelListResponse.java
  src/main/java/withbeetravel/exception/error/AuthErrorCode.java
  src/main/java/withbeetravel/exception/error/TravelErrorCode.java
  src/main/java/withbeetravel/exception/error/UserErrorCode.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#108 [Feat/TK-141] 공동결제내역 NPE 에러 해결
  src/main/java/withbeetravel/controller/payment/SharedPaymentController.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentResponse.java
  src/main/java/withbeetravel/service/payment/SharedPaymentServiceImpl.java
Labels: 🐞bug

#107 [Feat/TK-187] 인증인가 에러 수정 및 지출 상세 내역 조회 API 수정
  src/main/java/withbeetravel/config/SecurityConfig.java
  src/main/java/withbeetravel/controller/auth/AuthController.java
  src/main/java/withbeetravel/domain/RoleType.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/dto/request/auth/CustomUserInfoDto.java
  src/main/java/withbeetravel/dto/response/auth/ExpirationDto.java
  src/main/java/withbeetravel/dto/response/settlement/ShowMyTotalPaymentResponse.java
  src/main/java/withbeetravel/dto/response/travel/TravelListResponse.java
  src/main/java/withbeetravel/exception/error/AuthErrorCode.java
  src/main/java/withbeetravel/exception/handler/CustomExceptionHandler.java
  src/main/java/withbeetravel/jwt/JwtUtil.java
  src/main/java/withbeetravel/repository/TravelMemberRepository.java
  src/main/java/withbeetravel/service/auth/AuthServiceImpl.java
  src/main/java/withbeetravel/service/auth/RefreshTokenService.java
  src/main/java/withbeetravel/service/auth/RefreshTokenServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: 🐞bug

#115 [Feat/TK-187]: 상세 내역 조회 API 수정
  src/main/java/withbeetravel/dto/response/settlement/MyDetailPaymentResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowMyDetailPaymentResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowMyTotalPaymentResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowOtherSettlementResponse.java
  src/main/java/withbeetravel/dto/response/settlement/ShowSettlementDetailResponse.java
  src/main/java/withbeetravel/repository/PaymentParticipatedMemberRepository.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: 🐞bug

#111 [hotfix]: userId UserAuthorizationUtil에서 가져오도록 수정
  src/main/java/withbeetravel/aspect/TravelAccessAspect.java
  src/main/java/withbeetravel/aspect/TravelAndSharedPaymentAccessAspect.java
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentController.java
  src/main/java/withbeetravel/controller/payment/SharedPaymentRegisterController.java
Labels: 🚨 hotfix

#119 Feat/tk 200 cicd 적용하기
  .github/workflows/depoly-desktop.yml
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/aspect/BankingAccessAspect.java
  src/main/java/withbeetravel/aspect/CheckBankingAccess.java
  src/main/java/withbeetravel/config/CorsConfig.java
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/controller/banking/VerifyController.java
  src/main/java/withbeetravel/repository/AccountRepository.java
  src/main/java/withbeetravel/service/banking/VerifyServiceImpl.java
Labels: ✨ feature

#121 [Feat/tk 208] - 카드 발급 여부 api 구현
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/domain/Account.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/dto/request/account/CardCompletedRequest.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#122 Feat/tk 207 위비 카드 결제 내역 날짜 오름차순 정렬 추가
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: 🚨 hotfix

#125 [feat/TK-213]: 통화 코드 리스트 불러오기 API 구현
  src/main/java/withbeetravel/controller/payment/SharedPaymentRegisterController.java
  src/main/java/withbeetravel/controller/payment/docs/SharedPaymentRegisterControllerDocs.java
  src/main/java/withbeetravel/dto/response/payment/CurrencyUnitResponse.java
  src/main/java/withbeetravel/repository/TravelCountryRepository.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
Labels: ✨ feature

#130 [hotfix/TK-220]: 여행 기록 추가/수정 API 에러 수정
  src/main/java/withbeetravel/controller/payment/SharedPaymentRecordController.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecordService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecoredServiceImpl.java
Labels: 🐞bug, 🚨 hotfix

#127 Feat/tk 210 https 연결
  .github/workflows/depoly-desktop.yml
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/controller/banking/AccountController.java
  src/main/java/withbeetravel/domain/User.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
Labels: ♻️ refactor

#128 [feat/TK-183]: 여행 홈 API 필드 추가
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/domain/TravelMember.java
  src/main/java/withbeetravel/dto/response/travel/TravelHomeResponse.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#116 [Feat/TK-202] 정산 내역 정리 로그 및 정산 재요청 로그 추가 기능 구현
  src/main/java/withbeetravel/WithbeetravelApplication.java
  src/main/java/withbeetravel/config/TaskSchedulerConfig.java
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/dto/request/settlementRequestLog/SettlementRequestLogDto.java
  src/main/java/withbeetravel/exception/error/SettlementErrorCode.java
  src/main/java/withbeetravel/repository/SettlementRequestLogRepository.java
  src/main/java/withbeetravel/repository/TravelRepository.java
  src/main/java/withbeetravel/scheduler/SettlementRequestLogScheduler.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogService.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogServiceIml.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementPendingService.java
  src/main/java/withbeetravel/service/settlement/SettlementPendingServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#132 [Feat/TK-215] 로그아웃 기능 추가 및 refresh token 관리 방식 변경
  src/main/java/withbeetravel/config/SecurityConfig.java
  src/main/java/withbeetravel/controller/auth/AuthController.java
  src/main/java/withbeetravel/domain/RefreshToken.java
  src/main/java/withbeetravel/dto/request/auth/CustomUserInfo.java
  src/main/java/withbeetravel/dto/request/auth/RefreshTokenDto.java
  src/main/java/withbeetravel/dto/request/auth/SignInRequest.java
  src/main/java/withbeetravel/dto/request/auth/SignUpRequest.java
  src/main/java/withbeetravel/dto/response/auth/AccessTokenResponse.java
  src/main/java/withbeetravel/dto/response/auth/ExpirationDto.java
  src/main/java/withbeetravel/dto/response/auth/ExpirationResponse.java
  src/main/java/withbeetravel/dto/response/auth/ReissueResponse.java
  src/main/java/withbeetravel/dto/response/auth/SignInResponse.java
  src/main/java/withbeetravel/dto/response/auth/SignInResponseDto.java
  src/main/java/withbeetravel/dto/response/auth/UserAuthResponse.java
  src/main/java/withbeetravel/jwt/RefreshToken.java
  src/main/java/withbeetravel/repository/RefreshTokenRepository.java
  src/main/java/withbeetravel/security/CookieUtil.java
  src/main/java/withbeetravel/security/CustomUserDetails.java
  src/main/java/withbeetravel/service/auth/AuthService.java
  src/main/java/withbeetravel/service/auth/AuthServiceImpl.java
  src/main/java/withbeetravel/service/auth/CustomUserDetailsService.java
  src/main/java/withbeetravel/service/auth/RefreshTokenService.java
  src/main/java/withbeetravel/service/auth/RefreshTokenServiceImpl.java
Labels: ✨ feature

#134 [Feat/TK-215]: User 엔티티 수정
  src/main/java/withbeetravel/domain/User.java
Labels: 🐞bug
