Repository woorifisa-projects-3rd/WithBeeTravel-BE, pull requests merged in 2024-12, with the labels that each got.

#137 [feat/TK-228]: 위비 카드 결제 내역 추가 시 공동 결제 내역에 자동 추가되는 로직 구현
  src/main/java/withbeetravel/aspect/BankingAccessAspect.java
  src/main/java/withbeetravel/controller/banking/HistoryController.java
  src/main/java/withbeetravel/controller/banking/docs/HistoryControllerDocs.java
  src/main/java/withbeetravel/dto/request/account/HistoryRequest.java
  src/main/java/withbeetravel/service/banking/HistoryService.java
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
Labels: ✨ feature

#141 [Feat/TK-226] 실시간 알림 기능구현
  src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/domain/SettlementRequestLog.java
  src/main/java/withbeetravel/repository/notification/EmitterRepository.java
  src/main/java/withbeetravel/repository/notification/EmitterRepositoryImpl.java
  src/main/java/withbeetravel/service/notification/NotificationService.java
  src/main/java/withbeetravel/service/notification/NotificationServiceImpl.java
  src/main/java/withbeetravel/service/notification/SettlementRequestLogServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementPendingServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ✨ feature

#142 Feat/tk 224 관리자 페이지 api 구현
  src/main/java/withbeetravel/controller/banking/AccountController.java
Labels: 🚨 hotfix

#148 [Feat/TK-253] 테스트 코드 Fixture 작성
  src/test/java/withbeetravel/service/settlement/SettlementServiceTest.java
  src/test/java/withbeetravel/support/AccountFixture.java
  src/test/java/withbeetravel/support/SettlementRequestFixture.java
  src/test/java/withbeetravel/support/SettlementRequestLogFixture.java
  src/test/java/withbeetravel/support/SharedPaymentFixture.java
  src/test/java/withbeetravel/support/TravelFixture.java
  src/test/java/withbeetravel/support/UserFixture.java
Labels: ✨ feature

#149 [Feat/tk 253] CorsConfig 수정
  src/main/java/withbeetravel/config/CorsConfig.java
Labels: 🐞bug

#152 [feat/TK-253] CorsConfig 수정
  src/main/java/withbeetravel/config/CorsConfig.java
Labels: 🐞bug

#154 [feat/TK-253] CorsConfig 수정
  src/main/java/withbeetravel/config/CorsConfig.java
Labels: 🐞bug

#140 [feat/TK-141]: 새로운 멤버 기존 공동결제내역 참여멤버에 추가
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ✨ feature

#156 Feat/tk 253 테스트 코드 작성
  src/main/java/withbeetravel/config/CorsConfig.java
Labels: 🐞bug

#157 [feat/TK-224]:S3Config 설정 변경
  src/main/java/withbeetravel/config/S3Config.java
Labels: 🐞bug

#168 [Feat/TK-253] sse 컨트롤러 수정
  src/main/java/withbeetravel/controller/settlement/SettlementRequestLogController.java
Labels: 🚨 hotfix

#171 [Feat/TK-253] 정산 관련 테스트 코드 작성 및 API 수정
  build.gradle
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
  src/test/java/withbeetravel/controller/settlement/SettlementControllerTest.java
  src/test/java/withbeetravel/service/auth/AuthServiceTest.java
  src/test/java/withbeetravel/service/settlement/SettlementServiceTest.java
  src/test/java/withbeetravel/support/BaseIntegrationTest.java
  src/test/java/withbeetravel/support/SettlementTestFixture.java
  src/test/java/withbeetravel/support/TestData.java
Labels: ✨ feature

#170 Feat/tk 260 에러 수정 및 테스트 코드 작성
  src/main/java/withbeetravel/controller/payment/SharedPaymentParticipantController.java
  src/main/java/withbeetravel/dto/request/payment/SharedPaymentParticipateRequest.java
  src/main/java/withbeetravel/dto/response/auth/MyPageResponse.java
  src/main/java/withbeetravel/dto/response/payment/SharedPaymentRecordResponse.java
  src/main/java/withbeetravel/service/payment/SharedPaymentParticipantService.java
  src/main/java/withbeetravel/service/payment/SharedPaymentParticipantServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecordServiceImpl.java
  src/test/java/withbeetravel/service/auth/AuthServiceTest.java
  src/test/java/withbeetravel/service/payment/SharedPaymentParticipantServiceTest.java
  src/test/java/withbeetravel/service/payment/SharedPaymentRecordServiceTest.java
  src/test/java/withbeetravel/service/payment/SharedPaymentRegisterServiceTest.java
Labels: 🚨 hotfix

#167 [feat/TK-264]:여행 서비스 테스트 코드 작성
  src/test/java/withbeetravel/service/travel/TravelServiceImplTest.java
Labels: ✨ feature

#173 [Feat/tk 214] - 여행 조회 리스트 수정
  gradlew
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/dto/response/travel/TravelListResponse.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: ♻️ refactor

#176 [Feat/TK-253] 스케줄러 수정
  src/main/java/withbeetravel/DataLoader.java
  src/main/java/withbeetravel/config/TaskSchedulerConfig.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: 🐞bug, ♻️ refactor

#177 [refactor/TK-253] 여행 멤버 초대 코드 알림 추가
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: 🐞bug

#174 Feat/tk 260 허니 캡슐에 추가한 멤버 프로필 이미지 추가
  src/main/java/withbeetravel/controller/travel/TravelController.java
  src/main/java/withbeetravel/controller/travel/docs/TravelControllerDocs.java
  src/main/java/withbeetravel/dto/response/travel/HoneyCapsuleResponse.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRecordServiceImpl.java
  src/main/java/withbeetravel/service/payment/SharedPaymentRegisterServiceImpl.java
  src/main/java/withbeetravel/service/travel/TravelService.java
  src/main/java/withbeetravel/service/travel/TravelServiceImpl.java
Labels: 🚨 hotfix

#182 [fix/TK-275]: 허니캡슐 여행 기록 없는 결제 내역까지 불려오는 에러 수정
  src/main/java/withbeetravel/service/travel/HoneyCapsuleServiceImpl.java
Labels: 🚨 hotfix

#184 [Feat/TK-253] 스케줄러 코드 수정
  src/main/java/withbeetravel/scheduler/SettlementRequestLogScheduler.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ♻️ refactor

#185 [feat/TK-273] :뱅킹 SSE 설정
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/banking/HistoryServiceImpl.java
Labels: ✨ feature

#186 Feat/tk 273 카카오톡 초대코드 api 수정
  src/main/java/withbeetravel/domain/LogTitle.java
  src/main/java/withbeetravel/service/banking/AccountServiceImpl.java
  src/main/java/withbeetravel/service/settlement/SettlementServiceImpl.java
Labels: ♻️ refactor
